# Generated by Django 6.0.5 on 2026-05-12 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('photo', models.URLField(verbose_name='Фото (ссылка)')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
            ],
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.AddField(
            model_name='movie',
            name='backdrop',
            field=models.URLField(blank=True, verbose_name='Фон (широкое фото)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(verbose_name='Постер (ссылка)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='movies.actor', verbose_name='Актёры'),
        ),
    ]
