# Generated by Django 6.0.5 on 2026-05-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_actor_alter_movie_options_movie_backdrop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Режиссер'),
        ),
    ]
