# Generated by Django 6.0.5 on 2026-05-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_category_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Director'),
        ),
    ]
